### empty request
GET http://localhost:4000/

###  404 err
GET http://localhost:4000/notexisting

### 
GET http://localhost:4000/index

### empty post request (err)
POST http://localhost:4000/post

### post request with JSON Body (new)
POST http://localhost:4000/post
Content-Type: application/json 

{
    "message": "this is my new message",
    "sender":"123456"
}

###
POST http://localhost:4000/post
Content-Type: application/json

{
    "message": "this is my neighbor's message",
    "sender":"811000"
}

###
POST http://localhost:4000/post
Content-Type: application/json

{
    "message": "this is my cat's messageaedkfrgru.akerhv.46gc789gyaewervdfvradrv/larog",
    "sender":"047000"
}

### get all posts
GET http://localhost:4000/post
Content-Type: application/json 

### post update request by id (ERROR example)
POST http://localhost:4000/post/63bb350affdcd210451b5929

{
    "message": "this is my allien's message",
    "sender":"001100"
}

### get post by id (WORKS)
GET http://localhost:4000/post/63bb350affdcd210451b5929



#--------------------------TEST AREA-------------------------------start

### post request with JSON Body (new)
POST http://localhost:4000/post
Content-Type: application/json 

{
    "message": "this is wolf, woof",
    "sender":"000777"
}

### post request with JSON Body (new)
POST http://localhost:4000/post
Content-Type: application/json 

{
    "message": "this is cat, meow",
    "sender":"000888"
}

#--------------------------TEST AREA-------------------------------end
### register request
POST http://localhost:4000/auth/register
Content-Type: application/json

{
    "email": "example@gmail.com",
    "password": "1234"
}

### login request
POST http://localhost:4000/auth/login
Authorization: jwt ab3746f20930e00d0f0538785256a2c88a9b51b513e894d44f2a75e2922017888bb0b0283fa6b95e2f3daefc1197408a8300c19f7e87ed85d7b7d7c0cc176030
Content-Type: application/json

{
    "email": "example@gmail.com",
    "password": "1234"
}

### logout request
POST http://localhost:4000/auth/logout 
Content-Type: application/json

{
    "email": "example@gmail.com"
}

# -----------------Authenticated Requests------------------------


### post request with JSON Body (new)
POST http://localhost:4000/post
Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MjA5NGJkYWY1YjdiYWQ1MjYwMDkyYSIsImlhdCI6MTY3OTg1NjgzNSwiZXhwIjoxNjc5OTQzMjM1fQ._iXALjfoS85Vin2v1-sd20iFDN0ahhkl3FQEfJe9z_w
Content-Type: application/json 

{
    "message": "This is authorized user's post",
    "sender": "000111"
}

# ----------------------Requests from app--------------------------------------------
### register request
POST http://localhost:4000/auth/register
Content-Type: application/json

{
    "_id": "",
    "email": "example+beka@gmail.com",
    "name": "Beka A",
    "password": "1234callme",
    "imageUrl": ""
}

### login request - email, password
POST http://localhost:4000/auth/login
Content-Type: application/json

{
    "email": "example+beka@gmail.com",
    "password": "1234callme"
}

# ### login request - by token - NEED UPDATE TOKEN ACCORDING TO RESPONSE FROM REGISTRATION
# POST http://localhost:4000/auth/login
# Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MjM5Y2JjZDQyODRiNjQwZDhmZWMyZSIsImlhdCI6MTY4MDA1NTQ5NCwiZXhwIjoxNjgwMDc3MDk0fQ.elPCCy3RKReJmUsCdzHLkMZEy2NRWTBIIXaqlAtw-Zw

### logout request
POST http://localhost:4000/auth/logout 
Content-Type: application/json

{
    "email": "example@gmail.com"
}

#--------------------------------
### post request with JSON Body (new)
POST http://localhost:4000/post
Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MjM5Y2JjZDQyODRiNjQwZDhmZWMyZSIsImlhdCI6MTY4MDA1NTQ5NCwiZXhwIjoxNjgwMDc3MDk0fQ.elPCCy3RKReJmUsCdzHLkMZEy2NRWTBIIXaqlAtw-Zw
Content-Type: application/json 

{
    "message": "This is authorized user's post",
    "sender": "000111"
}