### empty request
GET http://localhost:4000/

###  404 err
GET http://localhost:4000/notexisting

### 
GET http://localhost:4000/index

### empty post request (err)
POST http://localhost:4000/post

### post request with JSON Body
POST http://localhost:4000/post
Content-Type: application/json

{
    "message": "this is my new message",
    "sender":"123456"
}

###
POST http://localhost:4000/post
Content-Type: application/json

{
    "message": "this is my neughbor's message",
    "sender":"811000"
}