### empty request
GET http://localhost:4000/

###  404 err
GET http://localhost:4000/notexisting

### 
GET http://localhost:4000/index

### empty post request (err)
POST http://localhost:4000/post

### post request with JSON Body (new)
POST http://localhost:4000/post
Content-Type: application/json 

{
    "message": "this is my new message",
    "sender":"123456"
}

###
POST http://localhost:4000/post
Content-Type: application/json

{
    "message": "this is my neighbor's message",
    "sender":"811000"
}

###
POST http://localhost:4000/post
Content-Type: application/json

{
    "message": "this is my cat's messageaedkfrgru.akerhv.46gc789gyaewervdfvradrv/larog",
    "sender":"047000"
}

### get all posts
GET http://localhost:4000/post
Content-Type: application/json 

### post update request by id (ERROR example)
POST http://localhost:4000/post/63bb350affdcd210451b5929

{
    "message": "this is my allien's message",
    "sender":"001100"
}

### get post by id (WORKS)
GET http://localhost:4000/post/63bb350affdcd210451b5929



#--------------------------TEST AREA-------------------------------start

### post request with JSON Body (new)
POST http://localhost:4000/post
Content-Type: application/json 

{
    "message": "this is wolf, woof",
    "sender":"000777"
}

### post request with JSON Body (new)
POST http://localhost:4000/post
Content-Type: application/json 

{
    "message": "this is cat, meow",
    "sender":"000888"
}

#--------------------------TEST AREA-------------------------------end
### register request
POST http://localhost:4000/auth/register
Content-Type: application/json

{
    "email": "example@gmail.com",
    "password": "1234"
}

### login request
POST http://localhost:4000/auth/login
Content-Type: application/json

{
    "email": "example@gmail.com",
    "password": "1234"
}

### logout request
POST http://localhost:4000/auth/logout
